[package]
edition = "2021"
name = "internal-baml-prompt-parser"
version.workspace = true
authors.workspace = true
description.workspace = true
licence-file.workspace = true

[dependencies]
internal-baml-diagnostics = { path = "../diagnostics", version = "^0.0.1" }
log = "0.4.20"

pest = "2.1.3"
pest_derive = "2.1.0"


[features]
debug_parser = []
default = ["debug_parser"]
