[workspace]
resolver = "2"
members = [
  "baml-lib/*",
  "baml-cli",
  "baml-fmt",
  "baml-schema-wasm",
]

[workspace.dependencies]
serde_json = { version = "1", features = ["float_roundtrip", "preserve_order"] }
serde = { version = "1", features = ["derive"] }
indoc = "2.0.1"
libc = "=0.2.149" # Temporarily pin this to 0.2.149 until 0.2.150 is patched

# 
[workspace.package]
version = "0.1.1-canary.3"
authors = ["Gloo <contact@trygloo.com>"]

description = "BAiML Toolchain"
license-file = "LICENSE"

[workspace.metadata.workspaces]
allow_branch = "canary"
