[package]
edition = "2021"
name = "baml-cli"
version.workspace = true
authors.workspace = true
description.workspace = true
licence = "Apache-2.0"
licence-file.workspace = true

[dependencies]
baml = { path = "../baml/baml", version = "^0.0.1" }
check-latest = "1.0.2"
clap = { version = "4.4.6", features = ["derive"] }
colored = "2.0.4"
env_logger = "0.10.0"
glob = "0.3.1"
log = "0.4.20"
semver = "1.0.20"

[dev-dependencies]
base64 = "0.13.0"
dissimilar = "1.0.4"
expect-test = "1.1.0"
indoc.workspace = true
either = "1.8.1"
