[package]
edition = "2021"
name = "internal-baml-prompt-parser"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[dependencies]
internal-baml-diagnostics = { path = "../diagnostics" }
internal-baml-schema-ast = { path = "../schema-ast" }
log = "0.4.20"

pest = { version = "2.1.3", default-features = false }
pest_derive = {version = "2.1.0", default-features = false }
textwrap = "0.16.0"


[features]
debug_parser = []
default = []
