[package]
edition = "2021"
name = "internal-baml-core"
version.workspace = true
authors.workspace = true
description.workspace = true
licence = "Apache-2.0"
licence-file.workspace = true

[dependencies]
internal-baml-diagnostics = { path = "../diagnostics", version = "^0.0.1" }
internal-baml-schema-ast = { path = "../schema-ast", version = "^0.0.1" }
internal-baml-parser-database = { path = "../parser-database", version = "^0.0.1" }
serde.workspace = true
serde_json.workspace = true
enumflags2 = "0.7"


[dev-dependencies]
base64 = "0.13.0"
dissimilar = "1.0.4"
expect-test = "1.1.0"
indoc.workspace = true
either = "1.8.1"
