[package]
edition = "2021"
name = "jsonish"
version.workspace = true
authors.workspace = true
description.workspace = true

license-file.workspace = true

[dependencies]
internal-baml-core = { path = "../baml-core" }
colored = "2"
pest = "2.1.3"
indoc.workspace = true
log = "0.4.20"
strsim = "0.10.0"
serde_json.workspace = true
serde.workspace = true
jsonschema = "0.17.1"
anyhow.workspace = true
either = "1.10.0"
