[package]
name = "ruby_ffi"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
# This controls the name of the generated .so file
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
baml-runtime = { path = "../../../baml-runtime", features = [] }
baml-types.workspace = true
base64.workspace = true
env_logger.workspace = true
derive_more.workspace = true
futures.workspace = true
indexmap.workspace = true
log.workspace = true
magnus = { version = "0.6.4", default = false, features = ["rb-sys"] }
# Must be kept in sync with ../../Gemfile
rb-sys = { version = "0.9.97", features = [
  "global-allocator",
  "bindgen-rbimpls",
  "bindgen-deprecated-types",
  "stable-api",
  "stable-api-compiled-fallback",
] }
serde.workspace = true
serde_json.workspace = true
serde_magnus = "0.8.1"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
rb-sys-env = { version = "0.1" }
