[package]
edition = "2021"
name = "baml"
version.workspace = true
authors.workspace = true
description.workspace = true
licence = "Apache-2.0"
licence-file.workspace = true

[dependencies]
internal-baml-core = { path = "../baml-core", version = "^0.0.1" }


[dev-dependencies]
pretty_assertions = "1.4.0"
base64 = "0.13.0"
dissimilar = "1.0.4"
expect-test = "1.1.0"
indoc.workspace = true
either = "1.8.1"
strip-ansi-escapes = "0.2.0"

[target.'cfg(feature = "use-pyo3")'.dependencies]
internal-baml-core = { path = "../baml-core", version = "^0.0.1", features = ["use-pyo3"] }

[features]
use-pyo3 = ["internal-baml-core/use-pyo3"]
